# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSInstanceTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AWSSpotInstanceRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_instances', models.IntegerField(default=None, null=True, verbose_name='Number of Instances')),
                ('max_price', models.FloatField(default=None, null=True)),
                ('expiration_time', models.DurationField()),
                ('request_id', models.CharField(default=None, max_length=255, null=True)),
                ('instance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.AWSInstanceTypeModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
