# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0004_auto_20170827_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsspotinstancerequestmodel',
            name='iam_fleet_role',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='awsspotinstancerequestmodel',
            name='max_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='awsspotinstancerequestmodel',
            name='num_instances',
            field=models.IntegerField(default=0, verbose_name='Number of Instances'),
            preserve_default=False,
        ),
    ]
