# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_auto_20170827_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsspotinstancerequestmodel',
            name='iam_fleet_role',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
